if(EXISTS "/home/nkulshr/flux-sched/src/common/libintern/interned_string_test-b12d07c_tests.cmake")
  include("/home/nkulshr/flux-sched/src/common/libintern/interned_string_test-b12d07c_tests.cmake")
else()
  add_test(interned_string_test_NOT_BUILT-b12d07c interned_string_test_NOT_BUILT-b12d07c)
endif()
